name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Black
        run: pip install black

      - name: Run Black linter
        run: black --check .
